ci: inline validate-mirrors-and-standby.bash
For trivial scripts its better to inline. This makes it easier to debug,
faster iteration by simply flying rather than needing to commit, less
files for indirection, etc.

diff --git a/ci/generated/pipeline.yml b/ci/generated/pipeline.yml
--- a/ci/generated/pipeline.yml
+++ b/ci/generated/pipeline.yml
@@ -645,12 +645,25 @@ jobs:
           type: registry-image
           source:
             repository: gcr.io/data-gpdb-public-images/gpdb6-centos7-test-golang
-            tag: "latest"
+            tag: latest
         inputs:
           - name: gpupgrade_src
+          - name: ccp_src
           - name: cluster_env_files
         run:
-          path: gpupgrade_src/ci/scripts/validate-mirrors-and-standby.bash
+          path: bash
+          args:
+            - -c
+            - |
+              set -eux
+
+              ./ccp_src/scripts/setup_ssh_to_cluster.sh
+
+              # Load the finalize test library.
+              source gpupgrade_src/test/acceptance/helpers/finalize_checks.bash
+
+              echo 'Doing failover tests of mirrors and standby...'
+              validate_mirrors_and_standby /usr/local/greenplum-db-target mdw 5432
   ensure:
     <<: *set_failed
   on_success:
@@ -755,12 +768,25 @@ jobs:
           type: registry-image
           source:
             repository: gcr.io/data-gpdb-public-images/gpdb6-centos7-test-golang
-            tag: "latest"
+            tag: latest
         inputs:
           - name: gpupgrade_src
+          - name: ccp_src
           - name: cluster_env_files
         run:
-          path: gpupgrade_src/ci/scripts/validate-mirrors-and-standby.bash
+          path: bash
+          args:
+            - -c
+            - |
+              set -eux
+
+              ./ccp_src/scripts/setup_ssh_to_cluster.sh
+
+              # Load the finalize test library.
+              source gpupgrade_src/test/acceptance/helpers/finalize_checks.bash
+
+              echo 'Doing failover tests of mirrors and standby...'
+              validate_mirrors_and_standby /usr/local/greenplum-db-target mdw 5432
   ensure:
     <<: *set_failed
   on_success:
@@ -870,12 +896,25 @@ jobs:
           type: registry-image
           source:
             repository: gcr.io/data-gpdb-public-images/gpdb6-centos7-test-golang
-            tag: "latest"
+            tag: latest
         inputs:
           - name: gpupgrade_src
+          - name: ccp_src
           - name: cluster_env_files
         run:
-          path: gpupgrade_src/ci/scripts/validate-mirrors-and-standby.bash
+          path: bash
+          args:
+            - -c
+            - |
+              set -eux
+
+              ./ccp_src/scripts/setup_ssh_to_cluster.sh
+
+              # Load the finalize test library.
+              source gpupgrade_src/test/acceptance/helpers/finalize_checks.bash
+
+              echo 'Doing failover tests of mirrors and standby...'
+              validate_mirrors_and_standby /usr/local/greenplum-db-target mdw 5432
   ensure:
     <<: *set_failed
   on_success:
@@ -985,12 +1024,25 @@ jobs:
           type: registry-image
           source:
             repository: gcr.io/data-gpdb-public-images/gpdb6-centos7-test-golang
-            tag: "latest"
+            tag: latest
         inputs:
           - name: gpupgrade_src
+          - name: ccp_src
           - name: cluster_env_files
         run:
-          path: gpupgrade_src/ci/scripts/validate-mirrors-and-standby.bash
+          path: bash
+          args:
+            - -c
+            - |
+              set -eux
+
+              ./ccp_src/scripts/setup_ssh_to_cluster.sh
+
+              # Load the finalize test library.
+              source gpupgrade_src/test/acceptance/helpers/finalize_checks.bash
+
+              echo 'Doing failover tests of mirrors and standby...'
+              validate_mirrors_and_standby /usr/local/greenplum-db-target mdw 5432
   ensure:
     <<: *set_failed
   on_success:
@@ -1101,12 +1153,25 @@ jobs:
           type: registry-image
           source:
             repository: gcr.io/data-gpdb-public-images/gpdb6-centos7-test-golang
-            tag: "latest"
+            tag: latest
         inputs:
           - name: gpupgrade_src
+          - name: ccp_src
           - name: cluster_env_files
         run:
-          path: gpupgrade_src/ci/scripts/validate-mirrors-and-standby.bash
+          path: bash
+          args:
+            - -c
+            - |
+              set -eux
+
+              ./ccp_src/scripts/setup_ssh_to_cluster.sh
+
+              # Load the finalize test library.
+              source gpupgrade_src/test/acceptance/helpers/finalize_checks.bash
+
+              echo 'Doing failover tests of mirrors and standby...'
+              validate_mirrors_and_standby /usr/local/greenplum-db-target mdw 5432
   ensure:
     <<: *set_failed
   on_success:
@@ -1418,12 +1483,25 @@ jobs:
           type: registry-image
           source:
             repository: gcr.io/data-gpdb-public-images/gpdb6-centos7-test-golang
-            tag: "latest"
+            tag: latest
         inputs:
           - name: gpupgrade_src
+          - name: ccp_src
           - name: cluster_env_files
         run:
-          path: gpupgrade_src/ci/scripts/validate-mirrors-and-standby.bash
+          path: bash
+          args:
+            - -c
+            - |
+              set -eux
+
+              ./ccp_src/scripts/setup_ssh_to_cluster.sh
+
+              # Load the finalize test library.
+              source gpupgrade_src/test/acceptance/helpers/finalize_checks.bash
+
+              echo 'Doing failover tests of mirrors and standby...'
+              validate_mirrors_and_standby /usr/local/greenplum-db-target mdw 5432
   ensure:
     <<: *set_failed
   on_success:
@@ -1534,12 +1612,25 @@ jobs:
           type: registry-image
           source:
             repository: gcr.io/data-gpdb-public-images/gpdb6-centos7-test-golang
-            tag: "latest"
+            tag: latest
         inputs:
           - name: gpupgrade_src
+          - name: ccp_src
           - name: cluster_env_files
         run:
-          path: gpupgrade_src/ci/scripts/validate-mirrors-and-standby.bash
+          path: bash
+          args:
+            - -c
+            - |
+              set -eux
+
+              ./ccp_src/scripts/setup_ssh_to_cluster.sh
+
+              # Load the finalize test library.
+              source gpupgrade_src/test/acceptance/helpers/finalize_checks.bash
+
+              echo 'Doing failover tests of mirrors and standby...'
+              validate_mirrors_and_standby /usr/local/greenplum-db-target mdw 5432
   ensure:
     <<: *set_failed
   on_success:
@@ -1851,12 +1942,25 @@ jobs:
           type: registry-image
           source:
             repository: gcr.io/data-gpdb-public-images/gpdb6-centos7-test-golang
-            tag: "latest"
+            tag: latest
         inputs:
           - name: gpupgrade_src
+          - name: ccp_src
           - name: cluster_env_files
         run:
-          path: gpupgrade_src/ci/scripts/validate-mirrors-and-standby.bash
+          path: bash
+          args:
+            - -c
+            - |
+              set -eux
+
+              ./ccp_src/scripts/setup_ssh_to_cluster.sh
+
+              # Load the finalize test library.
+              source gpupgrade_src/test/acceptance/helpers/finalize_checks.bash
+
+              echo 'Doing failover tests of mirrors and standby...'
+              validate_mirrors_and_standby /usr/local/greenplum-db-target mdw 5432
   ensure:
     <<: *set_failed
   on_success:
